export default [
  {
    photo: 'https://wdfiles.ru/plugins/imageviewer/site/direct.php?s=95a47d&/elena.jpg',
    name: 'Елена Мандровская',
    position: 'Team Lead',
    ghLink: 'https://github.com/ElenMandrovskaya',
    work:'Созданием базовой структуры проекта. Координацией команды в правильном направлении. Соданием запросов на API (ApiService), кнопка "ScrollUp".',
  },
  {
    photo: 'https://wdfiles.ru/plugins/imageviewer/site/direct.php?s=7834bf&/oleh.jpg',
    name: 'Олег Филяк',
    position: 'Scrum Master',
    ghLink: 'https://github.com/OlehFilyak',
    work: 'Созданием спрайта и оптимизацией картинок. Версткой хедера и его динамическим изменением. Отрисовкой main page по клику на лого/кнопку "Home".',
  },
  {
    photo: 'https://wdfiles.ru/plugins/imageviewer/site/direct.php?s=44211d&/swetlana.jpg',
    name: 'Светлана Лазарева',
    position: 'Developer',
    ghLink: 'https://github.com/sweetlanas',
    work:'Версткой футера. Модалкой с информацией об участниках нашей команды.',
  },
  {
    photo: 'https://wdfiles.ru/plugins/imageviewer/site/direct.php?s=672096&/katrin.jpg',
    name: 'Екатерина Верещагина',
    position: 'Developer',
    ghLink: 'https://github.com/EkaterinaVEA',
    work:' Версткой карточки фильма открывающегося в модалке. Реализацией открытия и закрытия модалки.',
  },
   {
    photo: 'https://wdfiles.ru/plugins/imageviewer/site/direct.php?s=de6437&/oksana.jpg',
    name: 'Оксана Зеленевская',
    position: 'Developer',
    ghLink: 'https://github.com/OksanaZel',
    work:' Версткой и подключением номера страниц (пагинация) на главной странице.',
  },
  {
    photo: 'https://wdfiles.ru/plugins/imageviewer/site/direct.php?s=6d18b0&/inna.jpg',
    name: 'Инна Дмитренко',
    position: 'Developer',
    ghLink: 'https://github.com/inna-dmytrenko',
    work:'Версткой контейнера главной страницы для правильного позиционирования карточек фильмов. Кнопка трейлера.',
  },
  {
    photo: 'https://wdfiles.ru/plugins/imageviewer/site/direct.php?s=613b0d&/suzanna.jpg',
    name: 'Сюзанна Максимова',
    position: 'Developer',
    ghLink: 'https://github.com/Suizanna',
    work:' Реализацией поиска и отрисовки фильмов по ключевому слову.',
  },
  {
    photo: 'https://wdfiles.ru/plugins/imageviewer/site/direct.php?s=628a90&/dima.jpg',
    name: 'Дима Марьянченко',
    position: 'Developer',
    ghLink: 'https://github.com/dimamarjan',
    work:'Реализацией функционала кнопок: "Add to watched", "Add to queue", Отрисовка и реализация работы страницы "My Library" и отрисовкой библиотеки пользователя.',
  },
   {
    photo: 'https://wdfiles.ru/plugins/imageviewer/site/direct.php?s=e72968&/slava.jpg',
    name: 'Вячеслав Грач',
    position: 'Developer',
    ghLink: 'https://github.com/SlavaGrach',
    work:' Версткой и поключением Loader для асинхронных запросов. Рендер популярных фильмов на главную страницу.',
  },
    {
    photo: 'https://wdfiles.ru/plugins/imageviewer/site/direct.php?s=fcbd9d&/valentin.jpg',
    name: 'Валентин Демчук',
    position: 'Developer',
    ghLink: 'https://github.com/Walle888',
    work:' Отрисовкой фильмов "Watched" и "Queue" по нажатию на соответствующие кнопки.',
  },
]